 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  llava150k_en_sft:
    # data_dir: ${env.data_dir}/datasets
    data_type: images

    build_info:
      annotations:
        train:
          # url: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/llava_conver_single_turn_500k.json
          url: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/llava_conver_single_turn_257k_clean.json
          # storage: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/llava_conver_single_turn_500k.json
          storage: /mnt/pfs-guan-ssai/nlu/wanghanzi/data/multimodal-sft/llava_150k/en/llava_conver_single_turn_257k_clean.json
          # storage: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/multimodal-sft/llava_150k/zh/llava_instruct_150k_zh_lisft_history.json
          # storage: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/multimodal-sft/llava_150k/zh/llava_instruct_150k_zh_mapped.json
      images:
          storage: /mnt/pfs-guan-ssai/nlu/dingyifeng/data/COCO